### ISSUE TITLE
Have private init

### ISSUE THREAD

**Issue by equwal** [patrickt/emacs#1]
I just used your stuff in my config, thanks!

Anyway, since I just read the thing, I have a suggestion which I hope you will appreciate: 
You might have your own custom init for kludges, system bugfixes, etc. etc. and not push those here (e.g. your `~/src/` as default-dir, or user-full-name as you).

**Comment by patrickt** [comment]
Indeed! I stick settings like that into `custom.el` and load it [here](https://github.com/patrickt/emacs/blob/master/init.el#L74).
